name: "Setup PHP"

inputs:
  php_version:
    description: 'The PHP version to run'
    default: '8.4'
    required: false
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage:
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Test defaults
      run: |
        echo PHP version ${{ inputs.php_version }}
      shell: bash

    - name: Setup PHP with extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}
        ini-values: ${{ inputs.php_ini-values }}
        coverage: ${{ inputs.php_coverage }}
        tools: ${{ inputs.php_tools }}

    - name: Debug PHP version
      run: php -v
      shell: bash
