name: "Setup Composer with auth"

inputs:
  php_version:
    description: 'The PHP version to run'
    default: '8.4'
    required: false
  sd_github_access_token:
    description: 'Access token to set before running composer.'
    required: true
  composer_install_options:
    required: false
    default: '--no-progress --prefer-dist --optimize-autoloader'
    description: "Custom composer install options"

runs:
  using: "composite"
  steps:
    - name: Test defaults
      run: |
        echo ComInstall stuff ${{ inputs.composer_install_options }}
      shell: bash

    - name: Set directory for cache
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-PHP${{ inputs.php_version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-PHP${{ inputs.php_version }}-composer-

    - name: Install Composer dependencies
      env:
        COMPOSER_AUTH: |
          {
            "github-oauth": {
              "github.com": "${{ inputs.sd_github_access_token }}"
            }
          }
      run: composer install ${{ inputs.composer_install_options }}
      shell: bash
