name: "Repo-, PHP-, Composer setup"

inputs:
  php_version:
    description: 'The PHP version to run'
    default: '8.4'
    required: false
  sd_github_access_token:
    description: 'Access token to set before running composer.'
    required: true
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage:
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
  composer_install_options:
    required: false
    default: '--no-progress --prefer-dist --optimize-autoloader'
    description: "Custom composer install options"
  auth_json:
    required: false
    description: "Custom composer auth json"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Test defaults
      run: |
        echo PHP version ${{ inputs.php_version }}
        echo ComInstall stuff ${{ inputs.composer_install_options }}
      shell: bash

    - name: Add auth_json, if present (for Nova e.g.)
      shell: bash
      if: ${{ inputs.auth_json != '' }}
      run: echo '${{ inputs.auth_json }}' > "$GITHUB_WORKSPACE/auth.json"

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}
        ini-values: ${{ inputs.php_ini-values }}
        coverage: ${{ inputs.php_coverage }}
        tools: ${{ inputs.php_tools }}

    - name: Set directory for cache
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-PHP${{ inputs.php_version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-PHP${{ inputs.php_version }}-composer-

    - name: Install Composer dependencies
      env:
        COMPOSER_AUTH: |
          {
            "github-oauth": {
              "github.com": "${{ inputs.sd_github_access_token }}"
            }
          }
      run: composer install ${{ inputs.composer_install_options }}
      shell: bash

    - name: Debug PHP version
      run: php -v
      shell: bash
